name: Build and Attach Release Assets

on:
  release:
    types: [published, prereleased]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Build rewindtty
      run: make
    - name: Rename binary for Linux
      run: mv ./build/rewindtty ./build/rewindtty-linux-x64
    - name: Upload binary to release
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          ./build/rewindtty-linux-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
